### ISSUE TITLE
quick question about Interval_Max

### ISSUE THREAD

**Issue by eostermueller** [giltene/jHiccup#27]
What is the unit or measure for Interval_Max in hiccup.*.hlog file ?
`"StartTimestamp","Interval_Length","Interval_Max","Interval_Compressed_Histogram"`

Sure looks like milliseconds, but can't find it documented anywhere.

Thanks,
--Erik

**Comment by giltene** [comment]
Yes, for jHiccup logs that is milliseconds (as a real number printed with 3 decimal points resolution).
The log format is an HdrHistogram log. The encoded histogram is captured in nanosecond units, and the Interval_Max is reported (by default) in units that are 1,000,000.0 times that (which translates to milliseconds). The Interval_Max column is somewhat superfluous, as the value can be extracted from the encoded histogram itself. It is there for mainly human-readability (seeing just the timestamp and and the max is often useful when visually scanning text logs), and to make it easy for simple parsers that only need that information.

**Comment by eostermueller** [comment]
I consider myself a simple parser, so I'm glad to have it there.  Thanks Gil.
